package at.medevit.ecrit.pharmacy_at.application.util;

import java.io.FileOutputStream;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Date;

import org.eclipse.core.runtime.FileLocator;

import at.medevit.ecrit.pharmacy_at.core.SampleModel;
import at.medevit.ecrit.pharmacy_at.model.Pharmacy;
import at.medevit.ecrit.pharmacy_at.model.StockArticle;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

public class PrintInventoryPDF {
	private static String FILE = "C:/Users/Lucia/Desktop/Inventory.pdf";
	private static Font catFont = new Font(Font.FontFamily.HELVETICA, 18, Font.BOLD);
	private static Font smallBold = new Font(Font.FontFamily.HELVETICA, 12, Font.BOLD);
	private static Font tinyBold = new Font(Font.FontFamily.HELVETICA, 11, Font.BOLD);
	private static Font tableHeaderFont = new Font(Font.FontFamily.HELVETICA, 11, Font.BOLD,
		BaseColor.GRAY);
	
	public PrintInventoryPDF(){
		try {
			Document document = new Document();
			PdfWriter.getInstance(document, new FileOutputStream(FILE));
			document.open();
			addMetaData(document);
			addAddressHeader(document);
			addContent(document);
			document.close();
		} catch (DocumentException | IOException e) {
			e.printStackTrace();
		}
		
	}
	
	private static void addMetaData(Document document){
		document.addAuthor(System.getProperty("user.name"));
		document.addCreationDate();
		document.addProducer();
		document.addCreator(SampleModel.getPharmacy().getName());
		document.addTitle("Inventory Form");
	}
	
	private static void addAddressHeader(Document document) throws DocumentException,
		MalformedURLException, IOException{
		Paragraph preface = new Paragraph();
		
		URL url = PrintInventoryPDF.class.getResource("/icons/ecrit_logo.png");
		Image companyLogo = Image.getInstance(FileLocator.toFileURL(url));
		companyLogo.setAbsolutePosition(25, 730);
		companyLogo.scalePercent(20);
		preface.add(companyLogo);
		
		// Will create: Report generated by: _name, _date
		Pharmacy pharmacy = SampleModel.getPharmacy();
		Paragraph pharmacyName = new Paragraph(pharmacy.getName(), smallBold);
		pharmacyName.setAlignment(Element.ALIGN_RIGHT);
		preface.add(pharmacyName);
		
		Paragraph adrStreet = new Paragraph(pharmacy.getAddress().getStreet(), tinyBold);
		adrStreet.setAlignment(Element.ALIGN_RIGHT);
		preface.add(adrStreet);
		
		Paragraph adrPostCodeCity =
			new Paragraph(pharmacy.getAddress().getPostCode() + " "
				+ pharmacy.getAddress().getTown(), tinyBold);
		adrPostCodeCity.setAlignment(Element.ALIGN_RIGHT);
		preface.add(adrPostCodeCity);
		
		Paragraph adrCountry = new Paragraph(pharmacy.getAddress().getCountry(), tinyBold);
		adrCountry.setAlignment(Element.ALIGN_RIGHT);
		preface.add(adrCountry);
		
		addEmptyLine(preface, 1);
		preface.add(new Paragraph("Inventory Report", catFont));
		preface.add(new Paragraph("Created by: ..............................................,"
			+ new Date(), smallBold));
		addEmptyLine(preface, 3);
		
		document.add(preface);
	}
	
	private static void addContent(Document document) throws DocumentException{
		Paragraph invParagraph = new Paragraph();
		createTable(invParagraph);
		document.add(invParagraph);
	}
	
	private static void createTable(Paragraph paragraph) throws DocumentException{
		PdfPTable table = new PdfPTable(3);
		table.setHorizontalAlignment(Element.ALIGN_CENTER);
		table.setWidths(new int[] {
			70, 350, 100
		});
		
		PdfPCell c1 = new PdfPCell(new Phrase("OnStock", tableHeaderFont));
		c1.setHorizontalAlignment(Element.ALIGN_CENTER);
		table.addCell(c1);
		
		c1 = new PdfPCell(new Phrase("Article", tableHeaderFont));
		c1.setHorizontalAlignment(Element.ALIGN_CENTER);
		table.addCell(c1);
		
		c1 = new PdfPCell(new Phrase("AdmNr", tableHeaderFont));
		c1.setHorizontalAlignment(Element.ALIGN_CENTER);
		table.addCell(c1);
		
		table.setHeaderRows(1);
		
		for (StockArticle sa : SampleModel.getStock().getArticles()) {
			table.addCell(" ");
			table.addCell(sa.getArticle().getName());
			table.addCell(sa.getArticle().getAdmissionNumber() + "");
		}
		
		paragraph.add(table);
	}
	
	private static void addEmptyLine(Paragraph paragraph, int number){
		for (int i = 0; i < number; i++) {
			paragraph.add(new Paragraph(" "));
		}
	}
	
}
